package com.motrix.download.ui.theme

import androidx.compose.ui.graphics.Color

// Motrix brand colors - exact from original Motrix
val MotrixPrimary = Color(0xFF5B5BFA)
val MotrixPrimaryDark = Color(0xFF4A4AE0)
val MotrixPrimaryLight = Color(0xFF7C7CFA)

// Status colors - matching @shared/colors.json
val StatusActive = Color(0xFF5B5BEA)
val StatusWaiting = Color(0xFF737373)
val StatusPaused = Color(0xFF737373)
val StatusError = Color(0xFFFF6157)
val StatusComplete = Color(0xFF2ACB42)
val StatusRemoved = Color(0xFF737373)
val StatusSeeding = Color(0xFF2ACB42)

// Progress bar colors
val ProgressActive = Color(0xFF5B5BEA)
val ProgressError = Color(0xFFFF6157)
val ProgressComplete = Color(0xFF2ACB42)
val ProgressDefault = Color(0xFF737373)

// Light theme - Motrix exact
val LightBackground = Color(0xFFF4F5F7)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF0F0F5)
val LightOnBackground = Color(0xFF303133)
val LightOnSurface = Color(0xFF303133)
val LightOnSurfaceVariant = Color(0xFF909399)
val LightSubnavBackground = Color(0xFFF4F5F7)
val LightSubnavActive = Color(0xFFEAECF0)
val LightSubnavText = Color(0xFF4D515A)
val LightSubnavActiveText = Color(0xFF5B5BFA)
val LightTaskItemBackground = Color(0xFFFFFFFF)
val LightTaskItemBorder = Color(0xFFCCCCCC)
val LightTaskItemHoverBorder = Color(0xFF5B5BFA)
val LightTaskItemText = Color(0xFF505753)
val LightTaskActionColor = Color(0xFF9B9B9B)
val LightTaskActionHover = Color(0xFF5B5BFA)
val LightTaskActionBg = Color(0xFFFFFFFF)
val LightTaskActionBorder = Color(0xFFF5F5F5)
val LightPanelTitle = Color(0xFF303133)
val LightSpeedometerBg = Color(0xFFFFFFFF)
val LightSpeedometerBorder = Color(0xFFCCCCCC)
val LightSpeedometerValue = Color(0xFF5B5BFA)
val LightSpeedometerLabel = Color(0xFF9B9B9B)
val LightNoTask = Color(0xFFEEEEEE)
val LightNavBarBg = Color(0xFFFFFFFF)
val LightDivider = Color(0xFFDCDFE6)

// Dark theme - Motrix exact
val DarkBackground = Color(0xFF343434)
val DarkSurface = Color(0xFF343434)
val DarkSurfaceVariant = Color(0xFF2D2D2D)
val DarkOnBackground = Color(0xFFEEEEEE)
val DarkOnSurface = Color(0xFFEEEEEE)
val DarkOnSurfaceVariant = Color(0xFFAAAAAA)
val DarkSubnavBackground = Color(0xFF2D2D2D)
val DarkSubnavActive = Color(0xFF444444)
val DarkSubnavText = Color(0xFFAAAAAA)
val DarkSubnavActiveText = Color(0xFFFFFFFF)
val DarkTaskItemBackground = Color(0xFF2D2D2D)
val DarkTaskItemBorder = Color(0xFF555555)
val DarkTaskItemHoverBorder = Color(0xFF5B5BFA)
val DarkTaskItemText = Color(0xFFEEEEEE)
val DarkTaskActionColor = Color(0xFFEEEEEE)
val DarkTaskActionHover = Color(0xFF5B5BFA)
val DarkTaskActionBg = Color(0xFF4A4A4A)
val DarkTaskActionBorder = Color(0xFF5F5F5F)
val DarkPanelTitle = Color(0xFFFFFFFF)
val DarkSpeedometerBg = Color(0xFF333333)
val DarkSpeedometerBorder = Color(0xFF5F5F5F)
val DarkSpeedometerValue = Color(0xFF5B5BFA)
val DarkSpeedometerLabel = Color(0xFF9B9B9B)
val DarkNoTask = Color(0xFFAAAAAA)
val DarkNavBarBg = Color(0xFF343434)
val DarkDivider = Color(0xFF555555)

// Sidebar (always dark overlay)
val SidebarBackground = Color(0xCC000000)
val SidebarIcon = Color(0xFFFFFFFF)
